/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue Jan  9 22:22:14 2024
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 1561
#define M_10 1
#define M_11 15
#define M_15 1
#define M_16 15
#define M_27 3
#define M_33 1
#define M_34 15
#define M_36 1
#define M_37 15

// center of mass
#define L_1_6 -1.36
#define L_3_6 0.35

// inertia
#define IN_1_6 389.68
#define IN_5_6 2436.4
#define IN_9_6 2641.5
#define IN_1_11 0.1
#define IN_5_11 0.8
#define IN_9_11 0.1
#define IN_1_16 0.1
#define IN_5_16 0.8
#define IN_9_16 0.1
#define IN_1_34 0.1
#define IN_5_34 0.8
#define IN_9_34 0.1
#define IN_1_37 0.1
#define IN_5_37 0.8
#define IN_9_37 0.1

// body point
#define DPT_1_1 -0.02
#define DPT_2_1 -0.35
#define DPT_3_1 0.2
#define DPT_1_2 -0.02
#define DPT_2_2 0.35
#define DPT_3_2 0.2
#define DPT_2_3 0.35
#define DPT_2_4 -0.35
#define DPT_1_5 -2.78
#define DPT_2_5 -0.35
#define DPT_1_6 -2.78
#define DPT_2_6 -0.35
#define DPT_3_6 0.3
#define DPT_1_7 -2.78
#define DPT_2_7 0.35
#define DPT_1_8 -0.2
#define DPT_3_8 -0.05
#define DPT_1_9 -0.2
#define DPT_3_9 0.1
#define DPT_1_10 -2.78
#define DPT_2_10 0.35
#define DPT_3_10 0.3
#define DPT_2_11 0.35
#define DPT_3_11 0.3
#define DPT_1_12 -2.78
#define DPT_2_12 0.35
#define DPT_3_12 0.2
#define DPT_1_13 -2.78
#define DPT_2_13 -0.35
#define DPT_3_13 0.2
#define DPT_2_14 -0.35
#define DPT_3_14 0.3
#define DPT_1_15 -3.08
#define DPT_3_15 -0.05
#define DPT_2_16 -0.4
#define DPT_1_17 0.1
#define DPT_2_17 -0.2
#define DPT_1_18 -0.1
#define DPT_3_18 -0.1
#define DPT_1_19 0.02
#define DPT_3_19 -0.2
#define DPT_3_20 -0.1
#define DPT_2_22 0.4
#define DPT_1_23 0.1
#define DPT_2_23 0.2
#define DPT_1_24 0.02
#define DPT_3_24 -0.2
#define DPT_3_25 -0.1
#define DPT_1_26 -0.1
#define DPT_3_26 -0.1
#define DPT_2_28 0.4
#define DPT_2_29 0.3
#define DPT_2_30 -0.4
#define DPT_2_31 -0.3
#define DPT_2_32 -0.4
#define DPT_2_33 -0.3
#define DPT_2_34 0.4
#define DPT_2_35 0.3
#define DPT_1_36 0.3
#define DPT_2_36 0.55
#define DPT_3_38 0.25
#define DPT_1_39 0.3
#define DPT_2_39 -0.55
#define DPT_3_40 0.25
#define DPT_2_41 -0.25
#define DPT_2_42 0.25
#define DPT_1_43 0.1
#define DPT_2_43 -0.5
#define DPT_1_44 0.1
#define DPT_2_44 0.5
#define DPT_2_45 0.4
#define DPT_1_46 0.1
#define DPT_2_46 0.2
#define DPT_3_47 -0.2
#define DPT_3_48 -0.1
#define DPT_2_50 -0.4
#define DPT_1_51 0.1
#define DPT_2_51 -0.2
#define DPT_3_52 -0.1
#define DPT_3_53 -0.2
#define DPT_1_56 0.3
#define DPT_2_56 0.55
#define DPT_1_57 0.3
#define DPT_2_57 -0.55
#define DPT_3_58 0.25
#define DPT_3_59 0.25

// ============================================================ //

# endif
