/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue Jan  9 22:22:14 2024
 * --------------------------------------------------------
 *
 */
#ifndef USERMODEL_h
#define USERMODEL_h



#include "mbs_user_interface.h"
// ============================================================ //


struct UserModel 
{
    struct FrontSuspension{
        double K;
        double D;
        double L0;
        double C_bar;
    } FrontSuspension;
 
    struct RearSuspension{
        double K;
        double D;
        double L0;
        double C_bar;
    } RearSuspension;
 
    struct FrontTire{
        double R;
        double K;
    } FrontTire;
 
    struct RearTire{
        double R;
        double K;
    } RearTire;
 
    struct EquilQ{
        double Qpropulsion;
        double Qsteer;
    } EquilQ;
 
};

// ============================================================ //
 
# endif
