/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue Jan  9 22:22:14 2024
 * --------------------------------------------------------
 *
 */
#include "mbs_path.h"
#include "user_model.h"
#include "mbs_binder_public.h"
#include "mbs_loader.h"
#include "useful_functions.h"
#include "mbs_message.h"
#include "lut.h"
#include <math.h>
#include <float.h>

// ============================================================ //


UserModel* mbs_new_user_model() 
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));
    um->FrontSuspension.K = 0.0;
    um->FrontSuspension.D = 0.0;
    um->FrontSuspension.L0 = 0.0;
    um->FrontSuspension.C_bar = 0.0;
 
    um->RearSuspension.K = 0.0;
    um->RearSuspension.D = 0.0;
    um->RearSuspension.L0 = 0.0;
    um->RearSuspension.C_bar = 0.0;
 
    um->FrontTire.R = 0.0;
    um->FrontTire.K = 0.0;
 
    um->RearTire.R = 0.0;
    um->RearTire.K = 0.0;
 
    um->EquilQ.Qpropulsion = 0.0;
    um->EquilQ.Qsteer = 0.0;
 
    return um;
}

void mbs_delete_user_model(UserModel* um) 
{
    free(um);
}

 void mbs_load_user_model(MbsInfos* mbs_infos, UserModel* um) 
{
    int ind_state_value = 1;

    um->FrontSuspension.K = mbs_infos->user_models->user_model_list[0]->parameter_list[0]->value_list[1];
    um->FrontSuspension.D = mbs_infos->user_models->user_model_list[0]->parameter_list[1]->value_list[1];
    um->FrontSuspension.L0 = mbs_infos->user_models->user_model_list[0]->parameter_list[2]->value_list[1];
    um->FrontSuspension.C_bar = mbs_infos->user_models->user_model_list[0]->parameter_list[3]->value_list[1];
 
    um->RearSuspension.K = mbs_infos->user_models->user_model_list[1]->parameter_list[0]->value_list[1];
    um->RearSuspension.D = mbs_infos->user_models->user_model_list[1]->parameter_list[1]->value_list[1];
    um->RearSuspension.L0 = mbs_infos->user_models->user_model_list[1]->parameter_list[2]->value_list[1];
    um->RearSuspension.C_bar = mbs_infos->user_models->user_model_list[1]->parameter_list[3]->value_list[1];
 
    um->FrontTire.R = mbs_infos->user_models->user_model_list[2]->parameter_list[0]->value_list[1];
    um->FrontTire.K = mbs_infos->user_models->user_model_list[2]->parameter_list[1]->value_list[1];
 
    um->RearTire.R = mbs_infos->user_models->user_model_list[3]->parameter_list[0]->value_list[1];
    um->RearTire.K = mbs_infos->user_models->user_model_list[3]->parameter_list[1]->value_list[1];
 
    um->EquilQ.Qpropulsion = mbs_infos->user_models->user_model_list[4]->parameter_list[0]->value_list[1];
    um->EquilQ.Qsteer = mbs_infos->user_models->user_model_list[4]->parameter_list[1]->value_list[1];
 
}

 void mbs_bind_user_model(MbsInfos* mbs_infos, UserModel* um) 
{
    mbs_infos->user_models->user_model_list[0]->parameter_list[0]->val_ptr = &um->FrontSuspension.K;
    mbs_infos->user_models->user_model_list[0]->parameter_list[1]->val_ptr = &um->FrontSuspension.D;
    mbs_infos->user_models->user_model_list[0]->parameter_list[2]->val_ptr = &um->FrontSuspension.L0;
    mbs_infos->user_models->user_model_list[0]->parameter_list[3]->val_ptr = &um->FrontSuspension.C_bar;
 
    mbs_infos->user_models->user_model_list[1]->parameter_list[0]->val_ptr = &um->RearSuspension.K;
    mbs_infos->user_models->user_model_list[1]->parameter_list[1]->val_ptr = &um->RearSuspension.D;
    mbs_infos->user_models->user_model_list[1]->parameter_list[2]->val_ptr = &um->RearSuspension.L0;
    mbs_infos->user_models->user_model_list[1]->parameter_list[3]->val_ptr = &um->RearSuspension.C_bar;
 
    mbs_infos->user_models->user_model_list[2]->parameter_list[0]->val_ptr = &um->FrontTire.R;
    mbs_infos->user_models->user_model_list[2]->parameter_list[1]->val_ptr = &um->FrontTire.K;
 
    mbs_infos->user_models->user_model_list[3]->parameter_list[0]->val_ptr = &um->RearTire.R;
    mbs_infos->user_models->user_model_list[3]->parameter_list[1]->val_ptr = &um->RearTire.K;
 
    mbs_infos->user_models->user_model_list[4]->parameter_list[0]->val_ptr = &um->EquilQ.Qpropulsion;
    mbs_infos->user_models->user_model_list[4]->parameter_list[1]->val_ptr = &um->EquilQ.Qsteer;
 
}
 
 void mbs_print_user_model(UserModel* um) 
{

    printf("user_model->FrontSuspension.K=%f\n", um->FrontSuspension.K);
    printf("user_model->FrontSuspension.D=%f\n", um->FrontSuspension.D);
    printf("user_model->FrontSuspension.L0=%f\n", um->FrontSuspension.L0);
    printf("user_model->FrontSuspension.C_bar=%f\n", um->FrontSuspension.C_bar);
 
    printf("user_model->RearSuspension.K=%f\n", um->RearSuspension.K);
    printf("user_model->RearSuspension.D=%f\n", um->RearSuspension.D);
    printf("user_model->RearSuspension.L0=%f\n", um->RearSuspension.L0);
    printf("user_model->RearSuspension.C_bar=%f\n", um->RearSuspension.C_bar);
 
    printf("user_model->FrontTire.R=%f\n", um->FrontTire.R);
    printf("user_model->FrontTire.K=%f\n", um->FrontTire.K);
 
    printf("user_model->RearTire.R=%f\n", um->RearTire.R);
    printf("user_model->RearTire.K=%f\n", um->RearTire.K);
 
    printf("user_model->EquilQ.Qpropulsion=%f\n", um->EquilQ.Qpropulsion);
    printf("user_model->EquilQ.Qsteer=%f\n", um->EquilQ.Qsteer);
 
}
 
void mbs_get_user_model_size(int *n_user_model) 
{
    *n_user_model  = 5; 
}
 
void mbs_get_user_model_list(int *user_model_list) 
{
    user_model_list[1]  = 4; 
    user_model_list[2]  = 4; 
    user_model_list[3]  = 2; 
    user_model_list[4]  = 2; 
    user_model_list[5]  = 2; 

}

void mbs_save_um(FILE* stream, UserModel* um)
{
    if (isnan(um->FrontSuspension.K)) { fprintf(stream, "         s->user_model->FrontSuspension.K = NAN; \n");}
    else if (isinf(um->FrontSuspension.K)) { fprintf(stream, "        s->user_model->FrontSuspension.K = %d * INFINITY; \n", isinf(um->FrontSuspension.K));}
    else { fprintf(stream, "        s->user_model->FrontSuspension.K = %.*e;\n", DBL_DECIMAL_DIG - 1, um->FrontSuspension.K);}
    if (isnan(um->FrontSuspension.D)) { fprintf(stream, "         s->user_model->FrontSuspension.D = NAN; \n");}
    else if (isinf(um->FrontSuspension.D)) { fprintf(stream, "        s->user_model->FrontSuspension.D = %d * INFINITY; \n", isinf(um->FrontSuspension.D));}
    else { fprintf(stream, "        s->user_model->FrontSuspension.D = %.*e;\n", DBL_DECIMAL_DIG - 1, um->FrontSuspension.D);}
    if (isnan(um->FrontSuspension.L0)) { fprintf(stream, "         s->user_model->FrontSuspension.L0 = NAN; \n");}
    else if (isinf(um->FrontSuspension.L0)) { fprintf(stream, "        s->user_model->FrontSuspension.L0 = %d * INFINITY; \n", isinf(um->FrontSuspension.L0));}
    else { fprintf(stream, "        s->user_model->FrontSuspension.L0 = %.*e;\n", DBL_DECIMAL_DIG - 1, um->FrontSuspension.L0);}
    if (isnan(um->FrontSuspension.C_bar)) { fprintf(stream, "         s->user_model->FrontSuspension.C_bar = NAN; \n");}
    else if (isinf(um->FrontSuspension.C_bar)) { fprintf(stream, "        s->user_model->FrontSuspension.C_bar = %d * INFINITY; \n", isinf(um->FrontSuspension.C_bar));}
    else { fprintf(stream, "        s->user_model->FrontSuspension.C_bar = %.*e;\n", DBL_DECIMAL_DIG - 1, um->FrontSuspension.C_bar);}
 
    if (isnan(um->RearSuspension.K)) { fprintf(stream, "         s->user_model->RearSuspension.K = NAN; \n");}
    else if (isinf(um->RearSuspension.K)) { fprintf(stream, "        s->user_model->RearSuspension.K = %d * INFINITY; \n", isinf(um->RearSuspension.K));}
    else { fprintf(stream, "        s->user_model->RearSuspension.K = %.*e;\n", DBL_DECIMAL_DIG - 1, um->RearSuspension.K);}
    if (isnan(um->RearSuspension.D)) { fprintf(stream, "         s->user_model->RearSuspension.D = NAN; \n");}
    else if (isinf(um->RearSuspension.D)) { fprintf(stream, "        s->user_model->RearSuspension.D = %d * INFINITY; \n", isinf(um->RearSuspension.D));}
    else { fprintf(stream, "        s->user_model->RearSuspension.D = %.*e;\n", DBL_DECIMAL_DIG - 1, um->RearSuspension.D);}
    if (isnan(um->RearSuspension.L0)) { fprintf(stream, "         s->user_model->RearSuspension.L0 = NAN; \n");}
    else if (isinf(um->RearSuspension.L0)) { fprintf(stream, "        s->user_model->RearSuspension.L0 = %d * INFINITY; \n", isinf(um->RearSuspension.L0));}
    else { fprintf(stream, "        s->user_model->RearSuspension.L0 = %.*e;\n", DBL_DECIMAL_DIG - 1, um->RearSuspension.L0);}
    if (isnan(um->RearSuspension.C_bar)) { fprintf(stream, "         s->user_model->RearSuspension.C_bar = NAN; \n");}
    else if (isinf(um->RearSuspension.C_bar)) { fprintf(stream, "        s->user_model->RearSuspension.C_bar = %d * INFINITY; \n", isinf(um->RearSuspension.C_bar));}
    else { fprintf(stream, "        s->user_model->RearSuspension.C_bar = %.*e;\n", DBL_DECIMAL_DIG - 1, um->RearSuspension.C_bar);}
 
    if (isnan(um->FrontTire.R)) { fprintf(stream, "         s->user_model->FrontTire.R = NAN; \n");}
    else if (isinf(um->FrontTire.R)) { fprintf(stream, "        s->user_model->FrontTire.R = %d * INFINITY; \n", isinf(um->FrontTire.R));}
    else { fprintf(stream, "        s->user_model->FrontTire.R = %.*e;\n", DBL_DECIMAL_DIG - 1, um->FrontTire.R);}
    if (isnan(um->FrontTire.K)) { fprintf(stream, "         s->user_model->FrontTire.K = NAN; \n");}
    else if (isinf(um->FrontTire.K)) { fprintf(stream, "        s->user_model->FrontTire.K = %d * INFINITY; \n", isinf(um->FrontTire.K));}
    else { fprintf(stream, "        s->user_model->FrontTire.K = %.*e;\n", DBL_DECIMAL_DIG - 1, um->FrontTire.K);}
 
    if (isnan(um->RearTire.R)) { fprintf(stream, "         s->user_model->RearTire.R = NAN; \n");}
    else if (isinf(um->RearTire.R)) { fprintf(stream, "        s->user_model->RearTire.R = %d * INFINITY; \n", isinf(um->RearTire.R));}
    else { fprintf(stream, "        s->user_model->RearTire.R = %.*e;\n", DBL_DECIMAL_DIG - 1, um->RearTire.R);}
    if (isnan(um->RearTire.K)) { fprintf(stream, "         s->user_model->RearTire.K = NAN; \n");}
    else if (isinf(um->RearTire.K)) { fprintf(stream, "        s->user_model->RearTire.K = %d * INFINITY; \n", isinf(um->RearTire.K));}
    else { fprintf(stream, "        s->user_model->RearTire.K = %.*e;\n", DBL_DECIMAL_DIG - 1, um->RearTire.K);}
 
    if (isnan(um->EquilQ.Qpropulsion)) { fprintf(stream, "         s->user_model->EquilQ.Qpropulsion = NAN; \n");}
    else if (isinf(um->EquilQ.Qpropulsion)) { fprintf(stream, "        s->user_model->EquilQ.Qpropulsion = %d * INFINITY; \n", isinf(um->EquilQ.Qpropulsion));}
    else { fprintf(stream, "        s->user_model->EquilQ.Qpropulsion = %.*e;\n", DBL_DECIMAL_DIG - 1, um->EquilQ.Qpropulsion);}
    if (isnan(um->EquilQ.Qsteer)) { fprintf(stream, "         s->user_model->EquilQ.Qsteer = NAN; \n");}
    else if (isinf(um->EquilQ.Qsteer)) { fprintf(stream, "        s->user_model->EquilQ.Qsteer = %d * INFINITY; \n", isinf(um->EquilQ.Qsteer));}
    else { fprintf(stream, "        s->user_model->EquilQ.Qsteer = %.*e;\n", DBL_DECIMAL_DIG - 1, um->EquilQ.Qsteer);}
 
}

// ============================================================ //
 
