/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue Jan  9 22:22:14 2024
 * --------------------------------------------------------
 *
 */
#ifndef USER_ALL_ID_h
#define USER_ALL_ID_h

// ============================================================ //


// joint

#define T1_chassis_id 1
#define T2_chassis_id 2
#define T3_chassis_id 3
#define R3_chassis_id 4
#define R1_chassis_id 5
#define R2_chassis_id 6
#define Joint_16_id 7
#define Joint_4_id 8
#define Joint_17_id 9
#define Joint_18_id 10
#define R2_wheel_ft_rt_id 11
#define Joint_6_id 12
#define Joint_5_id 13
#define Joint_8_id 14
#define Joint_9_id 15
#define R2_wheel_ft_lt_id 16
#define R1_bras_inf_av_g_1_id 17
#define R1_bras_inf_av_d_1_id 18
#define R1_bras_inf_ar_d_1_id 19
#define R1_bras_inf_ar_g_1_id 20
#define Joint_11_id 21
#define Joint_21_id 22
#define Joint_22_id 23
#define R2_def_bar_ft_id 24
#define Joint_24_id 25
#define Joint_25_id 26
#define T2_rack_id 27
#define Joint_0_id 28
#define Joint_1_id 29
#define Joint_2_id 30
#define Joint_3_id 31
#define Joint_31_id 32
#define Joint_38_id 33
#define R2_wheel_rr_lt_id 34
#define Joint_27_id 35
#define Joint_28_id 36
#define R2_wheel_rr_rt_id 37
#define Joint_32_id 38
#define R2_def_bar_rr_id 39
#define Joint_34_id 40
#define Joint_35_id 41
#define Joint_40_id 42
#define Joint_41_id 43

static char *mbs_joints_name[] = {
	"ORIGIN",
	"T1_chassis",
	"T2_chassis",
	"T3_chassis",
	"R3_chassis",
	"R1_chassis",
	"R2_chassis",
	"Joint_16",
	"Joint_4",
	"Joint_17",
	"Joint_18",
	"R2_wheel_ft_rt",
	"Joint_6",
	"Joint_5",
	"Joint_8",
	"Joint_9",
	"R2_wheel_ft_lt",
	"R1_bras_inf_av_g_1",
	"R1_bras_inf_av_d_1",
	"R1_bras_inf_ar_d_1",
	"R1_bras_inf_ar_g_1",
	"Joint_11",
	"Joint_21",
	"Joint_22",
	"R2_def_bar_ft",
	"Joint_24",
	"Joint_25",
	"T2_rack",
	"Joint_0",
	"Joint_1",
	"Joint_2",
	"Joint_3",
	"Joint_31",
	"Joint_38",
	"R2_wheel_rr_lt",
	"Joint_27",
	"Joint_28",
	"R2_wheel_rr_rt",
	"Joint_32",
	"R2_def_bar_rr",
	"Joint_34",
	"Joint_35",
	"Joint_40",
	"Joint_41"
	};

// body

#define Chassis_1_id 6
#define Bras_sup_av_d_1_id 7
#define Fusee_av_d_1_id 10
#define Roue_av_d_1_id 11
#define Bras_sup_av_g_1_id 12
#define Fusee_av_g_1_id 15
#define Roue_av_g_1_id 16
#define Bras_inf_av_g_1_id 17
#define Bras_inf_av_d_1_id 18
#define Bras_inf_ar_d_1_id 19
#define Bras_inf_ar_g_1_id 20
#define BAR_av_g_1_id 21
#define Bielle_av_g_id 23
#define BAR_av_d_1_id 24
#define Bielle_av_d_1_id 26
#define Bar_direction_1_id 27
#define Bielle_dir_d_1_id 29
#define Bielle_dir_g_1_id 31
#define Bras_sup_ar_g_1_id 32
#define Fusee_ar_g_1_id 33
#define Roue_ar_g_1_id 34
#define Bras_sup_ar_d_1_id 35
#define Fusee_ar_d_1_id 36
#define Roue_ar_d_1_id 37
#define BAR_ar_g_1_id 38
#define BAR_ar_d_1_id 39
#define Bielle_ar_d_1_id 41
#define Bielle_ar_g_1_id 43

static char *mbs_bodies_name[] = {
	"INVALID BODY ID : this is the base body 0",
	"INVALID BODY ID : joint element.",
	"INVALID BODY ID : joint element.",
	"INVALID BODY ID : joint element.",
	"INVALID BODY ID : joint element.",
	"INVALID BODY ID : joint element.",
	"Chassis_1",
	"Bras_sup_av_d_1",
	"INVALID BODY ID : joint element.",
	"INVALID BODY ID : joint element.",
	"Fusee_av_d_1",
	"Roue_av_d_1",
	"Bras_sup_av_g_1",
	"INVALID BODY ID : joint element.",
	"INVALID BODY ID : joint element.",
	"Fusee_av_g_1",
	"Roue_av_g_1",
	"Bras_inf_av_g_1",
	"Bras_inf_av_d_1",
	"Bras_inf_ar_d_1",
	"Bras_inf_ar_g_1",
	"BAR_av_g_1",
	"INVALID BODY ID : joint element.",
	"Bielle_av_g",
	"BAR_av_d_1",
	"INVALID BODY ID : joint element.",
	"Bielle_av_d_1",
	"Bar_direction_1",
	"INVALID BODY ID : joint element.",
	"Bielle_dir_d_1",
	"INVALID BODY ID : joint element.",
	"Bielle_dir_g_1",
	"Bras_sup_ar_g_1",
	"Fusee_ar_g_1",
	"Roue_ar_g_1",
	"Bras_sup_ar_d_1",
	"Fusee_ar_d_1",
	"Roue_ar_d_1",
	"BAR_ar_g_1",
	"BAR_ar_d_1",
	"INVALID BODY ID : joint element.",
	"Bielle_ar_d_1",
	"Bielle_ar_g_1"
	};

// point

#define Chassis_1_to_bras_sup_av_d_1_id 1
#define Chassis_1_to_bras_sup_av_g_1_id 2
#define Chassis_1_Point_2_1_id 3
#define Chassis_1_Point_3_1_id 4
#define Chassis_1_Point_4_1_id 5
#define Chassis_1_Point_5_1_id 6
#define Chassis_1_Point_7_1_id 7
#define Chassis_1_Point_8_1_id 8
#define Chassis_1_Point_9_1_id 9
#define Chassis_1_Point_6_1_id 10
#define Chassis_1_Point_10_1_id 11
#define Chassis_1_to_bras_sup_ar_g_1_id 12
#define Chassis_1_to_bras_sup_ar_d_1_id 13
#define Chassis_1_Point_13_1_id 14
#define Chassis_1_Point_14_1_id 15
#define Bras_sup_av_d_1_L_bras_sup_av_d_1_id 16
#define Bras_sup_av_d_1_to_ball_id 17
#define Fusee_av_d_1_to_ball_dir_id 18
#define Fusee_av_d_1_to_ball_bras_inf_id 19
#define Fusee_av_d_1_to_roue_id 20
//#define Roue_av_d_1_origin_id 21
#define Bras_sup_av_g_1_L_bras_sup_av_g_1_id 22
#define Bras_sup_av_g_1_to_ball_id 23
#define Fusee_av_g_1_to_ball_bras_inf_id 24
#define Fusee_av_g_1_to_roue_id 25
#define Fusee_av_g_1_to_ball_dir_id 26
//#define Roue_av_g_1_origin_id 27
#define Bras_inf_av_g_1_Point_0_id 28
#define Bras_inf_av_g_1_Point_1_id 29
#define Bras_inf_av_d_1_Point_0_id 30
#define Bras_inf_av_d_1_Point_1_id 31
#define Bras_inf_ar_d_1_Point_0_id 32
#define Bras_inf_ar_d_1_Point_1_id 33
#define Bras_inf_ar_g_1_Point_0_id 34
#define Bras_inf_ar_g_1_Point_1_id 35
#define BAR_av_g_1_Point_0_id 36
#define BAR_av_g_1_Point_1_id 37
#define Bielle_av_g_Point_0_id 38
#define BAR_av_d_1_Point_0_id 39
#define Bielle_av_d_1_Point_0_id 40
#define Bar_direction_1_Point_0_id 41
#define Bar_direction_1_Point_1_id 42
#define Bielle_dir_d_1_Point_0_id 43
#define Bielle_dir_g_1_Point_0_id 44
#define Bras_sup_ar_g_1_L_bras_sup_ar_g_1_id 45
#define Bras_sup_ar_g_1_to_ball_id 46
#define Fusee_ar_g_1_to_ball_bras_inf_id 47
#define Fusee_ar_g_1_to_roue_id 48
//#define Roue_ar_g_1_origin_id 49
#define Bras_sup_ar_d_1_L_bras_sup_ar_d_1_id 50
#define Bras_sup_ar_d_1_to_ball_id 51
#define Fusee_ar_d_1_to_roue_id 52
#define Fusee_ar_d_1_to_ball_bras_inf_id 53
//#define Roue_ar_d_1_origin_id 54
#define BAR_ar_g_1_Point_0_id 55
#define BAR_ar_g_1_Point_1_id 56
#define BAR_ar_d_1_Point_0_id 57
#define Bielle_ar_d_1_Point_0_id 58
#define Bielle_ar_g_1_Point_0_id 59


// sensor


static char *mbs_sensors_name[] = {
	"INVALID SENSOR ID: 0"
	};

// extforce

#define F_av_d_1_id 1
#define F_av_g_1_id 2
#define F_ar_g_1_id 3
#define F_ar_d_1_id 4

static char *mbs_extforces_name[] = {
	"INVALID EXTFORCE ID: 0",
	"F_av_d_1",
	"F_av_g_1",
	"F_ar_g_1",
	"F_ar_d_1"
	};

// links

#define Amortisseur_av_g_1_id 1
#define Amortisseur_av_d_1_id 2
#define Amortisseur_ar_d_1_id 3
#define Amortisseur_ar_g_1_id 4

static char *mbs_links_name[] = {
	"INVALID LINK ID: 0",
	"Amortisseur_av_g_1",
	"Amortisseur_av_d_1",
	"Amortisseur_ar_d_1",
	"Amortisseur_ar_g_1"
	};

// links 3D


static char *mbs_links3D_name[] = {
	"INVALID LINK3D ID: 0"
	};

// Rods



// ============================================================ //

# endif
